---
- hosts: web
  become: yes
  tasks:
    - name: Install dependencies
      apt:
        name: ["docker.io", "nginx", "git"]
        state: present

    - name: Add user to docker group
      user:
        name: ubuntu
        groups: docker
        append: yes

    - name: Enable and start Docker
      systemd:
        name: docker
        enabled: yes
        state: started

    - name: Install Docker Compose
      get_url:
        url: https://github.com/docker/compose/releases/download/v2.21.0/docker-compose-linux-x86_64
        dest: /usr/local/bin/docker-compose
        mode: '0755'

    - name: Copy NGINX config
      copy:
        src: ../docker/nginx.conf
        dest: /etc/nginx/sites-available/default

    - name: Restart NGINX
      systemd:
        name: nginx
        state: restarted

    - name: Init Docker Swarm
      shell: docker swarm init || true

    - name: Deploy Yii2 app
      shell: docker stack deploy -c /home/ubuntu/app/docker-compose.yml yii2
